# NOTE: Generated By HttpRunner v3.1.6
# FROM: har/yinxiang.har


from httprunner import HttpRunner, Config, Step, RunRequest



class TestCaseYinxiang(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/third/membership/restful/v1/getUserMembershipList")
            .post(
                "https://app.yinxiang.com/third/membership/restful/v1/getUserMembershipList"
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "auth": "S=s31:U=1881e6e:E=1d0622adeee:C=186f53f2690:P=1dd:A=yx-osx-xauth-new:V=3:H=ac98dac2125178d70c2c97b75062b459",
                    "accept-encoding": "gzip, deflate, br",
                    "user-agent": "%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0/471886 CFNetwork/1335.0.3.1 Darwin/21.6.0",
                    "content-length": "0",
                    "accept-language": "zh-CN,zh-Hans;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "req_sec": '"U=1881e6e:P=/:E=18986c994c0:S=2e7c6337ad838405044225790d81e2cd"',
                    "_ga": "GA1.2.2145025416.1679151775",
                    "web50017PreUserGuid": "5620b7c1-55fc-44d5-9b4a-822896d38195",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 200)
            .assert_equal("body.message", "success")
        ),
    ]


if __name__ == "__main__":
    TestCaseYinxiang().test_start()
